kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: todo-api-quarkus
spec:
  to:
    kind: Service
    name: todo-api-quarkus
    weight: 100
  port:
    targetPort: todo-api-quarkus
  tls:
    termination: edge
  wildcardPolicy: None